export const MessageTypes = Object.freeze({
  GET_SCHEDULE: "GET_SCHEDULE",
  GET_COURSES: "GET_COURSES",
  EXPORT_CALENDAR: "EXPORT_CALENDAR",
  GET_AUTH_TOKEN: "GET_AUTH_TOKEN",
  SCHEDULE: "SCHEDULE",
  COURSES: "COURSES",
});
